### ISSUE TITLE
In debug mode an assertion in class loader fails when destoying the class loader

### ISSUE THREAD

**Issue by Rauldg** [envire/envire-envire_core#39] opened 2018-10-30 13:48 UTC
Discovered trying to fix [this other issue](https://github.com/envire/envire-envire_core/issues/37)

The same minimal example, but compiled in debug mode creates this behavior:

At https://github.com/ros/class_loader/blob/0.3.7/src/class_loader_core.cpp#L497

It triggers:

```
install/include/boost/thread/pthread/recursive_mutex.hpp:113: void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.
```

**Comment by arneboe** [comment] 2018-10-30 15:43
I am unable to reproduce the bug.
What boost version are you using? Can you upload a complete working example that I can use to test? Maybe there is something different between your minimal example implementation and mine.

**Comment by arneboe** [comment] 2018-10-30 15:59
ok, now am able to reproduce it :) Mistake on my side

**Comment by arneboe** [comment] 2018-10-30 16:41
Ok, I poked at it some more:

all boost::recursive_locks are destroyed by the libc exit_handler. After that happens the class_loader tries to lock them. I do not understand why libc calls the recursive_lock destructor, though. It shouldn't....

**Comment by arneboe** [comment] 2018-10-30 17:02
Found it:

This is in class_loader_core.cpp
```
boost::recursive_mutex & getLoadedLibraryVectorMutex()
/*****************************************************************************/
{
  static boost::recursive_mutex m;
  return m;
}
```

The mutex is static local while the class_loader is static. The class_loader is created before the mutex. Thus the mutex is destroyed before the class_loader. The class_loader tries to access the mutex during destruction and obviously fails. This is something that should be fixed upstream (might very well be, we are on a really old version of the class_loader).

**Comment by Rauldg** [comment] 2018-10-31 09:51
I don't think they changed this in their newer versions.

See:
https://github.com/ros/class_loader/blob/melodic-devel/src/class_loader_core.cpp#L48

If we had a minimal breaking example of Class Loader without the envire things we could propose a PR to the class loader guys.

**Comment by arneboe** [comment] 2018-11-01 10:18
Ok this is more complex than I though.

This is not an upstream bug. The upstream class_loader works fine as long as it is not statically allocated. 

What happens is:

(1) the class_loader is statically allocated (because we use base::Singleton)
(2) upon first usage of the class_loader its internal mutexes are statically allocated.
(3) after the main() ends the static memory is freed in the inverse order of creation, thus the mutexes are deleted first.
(4) now the class_loader is deleted, however inside the destructor it tries to access the mutexes and crashes because they have already been deleted.

My solution would be to manually delete the class_loader pointer at the end of main. I can do it in a hacky way for now but ultimately this needs an extension to base::Singleton

**Comment by arneboe** [comment] 2018-11-01 11:10
The bug has been fixed in branch https://github.com/envire/envire-envire_core/tree/fix-classLoader

I had to add a feature to base-logging thus for now this fork of base-logging is required:
https://github.com/envire/base-logging/tree/feature-add-destroy

**Closed by arneboe** 2018-11-01 11:10 UTC

**Comment by saarnold** [comment] 2018-11-01 12:37
Thanks for investigating this issue! :+1:

**Comment by arneboe** [comment] 2018-11-01 12:55
We should document somewhere that one needs to manually destroy the ClassLoader before the program ends, I guess?
